/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contender;


/**
 *
 * @author TCC S05 G10
 */
public class JFtelaprincipal extends javax.swing.JFrame {


    /**
     * Creates new form JFtelaprincipal
     */
    public JFtelaprincipal() {
        initComponents();
        setLocationRelativeTo(null);
         this.setResizable(false);
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBfacil = new javax.swing.JButton();
        jBnormal = new javax.swing.JButton();
        jBdificil = new javax.swing.JButton();
        jBajuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo das portas logicas");

        jBfacil.setText("Fácil");
        jBfacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfacilActionPerformed(evt);
            }
        });

        jBnormal.setText("Normal");
        jBnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnormalActionPerformed(evt);
            }
        });

        jBdificil.setText("Difícil");
        jBdificil.setToolTipText("");
        jBdificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdificilActionPerformed(evt);
            }
        });

        jBajuda.setText("Ajuda");
        jBajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBajudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBdificil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBfacil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBajuda)
                .addGap(89, 89, 89)
                .addComponent(jBfacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBnormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBdificil)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBfacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfacilActionPerformed
// abre tela do jogo facil        // TODO add your handling code here:
JFfacil obj = new JFfacil();
obj.setVisible(true);
obj.fase(1);
dispose();

    }//GEN-LAST:event_jBfacilActionPerformed

    private void jBnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnormalActionPerformed
JFnormalfase1 obj = new JFnormalfase1();

obj.setVisible(true);  
obj.fase(11);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jBnormalActionPerformed

    private void jBdificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdificilActionPerformed
JFdificilfase1 obj = new JFdificilfase1();
obj.setVisible(true);  
obj.fase(21);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBdificilActionPerformed

    private void jBajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBajudaActionPerformed
 JFajuda obj = new JFajuda();
         obj.setVisible(true);  
         dispose();  
         // TODO add your handling code here:
    }//GEN-LAST:event_jBajudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFtelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFtelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFtelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFtelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFtelaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBajuda;
    private javax.swing.JButton jBdificil;
    private javax.swing.JButton jBfacil;
    private javax.swing.JButton jBnormal;
    // End of variables declaration//GEN-END:variables
}
